/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package my.oauth.authserver;

import java.io.File;

import org.apache.catalina.Context;
import org.apache.catalina.LifecycleException;
import org.apache.catalina.startup.Tomcat;
import org.apache.tomcat.util.descriptor.web.ErrorPage;

import my.oauth.servlets.Authorizer;
import my.oauth.servlets.Token;
import my.oauth.utils.Client;

public class AuthServer {
	public String getGreeting() {
		return "Hello world.";
	}

	private static final int port = 8002;

	private static void initClient() {
		Client.setClient_id("oauth-client-1");
		Client.setClient_secret("oauth-client-secret-1");
		Client.setRedirect_uris(new String[] { "http://localhost:8001/callback" });
		Client.setScope(new String[] { "foo", "bar" });
	}

	public static void main(String[] args) {

		initClient();

		Tomcat tomcat = new Tomcat();
		tomcat.setPort(port);
		tomcat.getConnector();
		String contextPath = "";
		String templateBase = new File("src/main/resources/templates").getAbsolutePath();
		Context templateContext = tomcat.addWebapp(contextPath, templateBase);

		ErrorPage ep = new ErrorPage();
		ep.setErrorCode(404);
		ep.setLocation("/error.html");
		templateContext.addErrorPage(ep);
		templateContext.addMimeMapping("ext", "type");

		tomcat.addWebapp("/js/", new File("src/main/resources/static/js").getAbsolutePath());
		tomcat.addWebapp("/css/", new File("src/main/resources/static/css").getAbsolutePath());

		Tomcat.addServlet(templateContext, "MainServlet", new MainServlet());
		Tomcat.addServlet(templateContext, "Authorizer", new Authorizer());
		Tomcat.addServlet(templateContext, "Token", new Token());
		templateContext.addServletMappingDecoded("", "MainServlet");
		templateContext.addServletMappingDecoded("/authorize", "Authorizer");
		templateContext.addServletMappingDecoded("/approve", "Authorizer");
		templateContext.addServletMappingDecoded("/token", "Token");

		try {
			tomcat.start();
			tomcat.getServer().await();
		} catch (LifecycleException e) {

			e.printStackTrace();
		}

	}
}
