/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package my.oauth.authserver;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        AuthServer classUnderTest = new AuthServer();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
