/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package my.oauth.app;

import java.io.File;

import org.apache.catalina.Context;
import org.apache.catalina.LifecycleException;
import org.apache.catalina.startup.Tomcat;
import org.apache.tomcat.util.descriptor.web.ErrorPage;

public class ClientOAuth {
	public String getGreeting() {
		return "Hello world.";
	}

	public static void main(String[] args) {
		Tomcat tomcat = new Tomcat();
		tomcat.setPort(8001);
		tomcat.getConnector();
		String contextPath = "";
		File base = new File(System.getProperty("java.io.tmpdir"));
		String docBase = base.getAbsolutePath();
		String templateBase = new File("src/main/resources/templates").getAbsolutePath();
		Context templateContext = tomcat.addWebapp(contextPath, templateBase);

		ErrorPage ep = new ErrorPage();
		ep.setErrorCode(404);
		ep.setLocation("/error.html");
		templateContext.addErrorPage(ep);
		templateContext.addMimeMapping("ext", "type");

		tomcat.addWebapp("/js/", new File("src/main/resources/static/js").getAbsolutePath());
		tomcat.addWebapp("/css/", new File("src/main/resources/static/css").getAbsolutePath());

		Tomcat.addServlet(templateContext, "MainServlet", new MainServlet());
		templateContext.addServletMappingDecoded("/app", "MainServlet");
		try {
			tomcat.start();
			tomcat.getServer().await();
		} catch (LifecycleException e) {

			e.printStackTrace();
		}

	}
}
