/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package my.oauth.app;

import java.io.File;

import org.apache.catalina.Context;
import org.apache.catalina.LifecycleException;
import org.apache.catalina.startup.Tomcat;
import org.apache.tomcat.util.descriptor.web.ErrorPage;

public class ClientOAuth {
	
	private static final String ERROR_PAGE = "/error.html";
	private static final int ERROR_CODE = 404;
	
	public String getGreeting() {
		return "Hello world.";
	}
	private static void setErrorPage( Context templateContext ) {
		ErrorPage ep = new ErrorPage();
		ep.setErrorCode( ERROR_CODE );
		ep.setLocation( ERROR_PAGE );
		templateContext.addErrorPage(ep);
		
	}
	public static void main(String[] args) {
		Tomcat tomcat = new Tomcat();
		tomcat.setPort(8001);
		tomcat.getConnector();
		String contextPath = "";
		String templateBase = new File("src/main/resources/templates").getAbsolutePath();
		Context templateContext = tomcat.addWebapp(contextPath, templateBase);
		
		setErrorPage( templateContext );
		
		templateContext.addMimeMapping("ext", "type");
		tomcat.addWebapp("/js/", new File("src/main/resources/static/js").getAbsolutePath());
		tomcat.addWebapp("/css/", new File("src/main/resources/static/css").getAbsolutePath());

		Tomcat.addServlet(templateContext, "MainServlet", new MainServlet());
		Tomcat.addServlet(templateContext, "Auth", new Auth());
		
		templateContext.addServletMappingDecoded("", "MainServlet");
		templateContext.addServletMappingDecoded("/auth", "Auth");
		
		
		try {
			tomcat.start();
			tomcat.getServer().await();
		} catch (LifecycleException e) {

			e.printStackTrace();
		}

	}
}
