/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package my.oauth.prote.server;

import java.io.File;

import org.apache.catalina.Context;
import org.apache.catalina.LifecycleException;
import org.apache.catalina.startup.Tomcat;
import org.apache.tomcat.util.descriptor.web.ErrorPage;
import org.apache.tomcat.util.descriptor.web.LoginConfig;

import my.oauth.servlets.Main;
import my.oauth.servlets.ResourceFetcher;


public class App {
    public String getGreeting() {
        return "Hello world.";
    }
    static final int port = 8003;
    
    public static void main(String[] args) {
    	
    	
    	Tomcat tomcat = new Tomcat();
		tomcat.setPort(port);
		tomcat.getConnector();
		String contextPath = "";
		String templateBase = new File("src/main/resources/templates").getAbsolutePath();
		Context templateContext = tomcat.addWebapp(contextPath, templateBase);

		ErrorPage ep = new ErrorPage();
		ep.setErrorCode(404);
		ep.setLocation("/error.html");
		templateContext.addErrorPage(ep);
		templateContext.addMimeMapping("ext", "type");

		
		
		
		tomcat.addWebapp("/js/", new File("src/main/resources/static/js").getAbsolutePath());
		tomcat.addWebapp("/css/", new File("src/main/resources/static/css").getAbsolutePath());

		Tomcat.addServlet(templateContext, "Main", new Main());
		Tomcat.addServlet(templateContext, "ResourceFetcher", new ResourceFetcher());
		templateContext.addServletMappingDecoded("", "Main");
		templateContext.addServletMappingDecoded("/resource", "ResourceFetcher");
		try {
			tomcat.start();
			tomcat.getServer().await();
		} catch (LifecycleException e) {

			e.printStackTrace();
		}
    }
}
